### ISSUE TITLE
When using Margins, the selection receives an offset

### ISSUE THREAD

**Issue by stefanspieler** [kupe517/sketch-split-shape#2]
![screenshot](https://user-images.githubusercontent.com/2961015/36302031-326109dc-1307-11e8-8f35-a9727d9f4786.png)
When using a Margin while splitting, the selection receives an offset from it origianl position, thats not fatal, but its a bit annoying. 

Using Sketch 48.2 (47372)

**Comment by kupe517** [comment]
@stefanspieler I need to do some upkeep on this plugin! I'd like to rewrite using the new javascript API at some point. The bug you are experiencing occurs when the shape you are splitting is not on an artboard. If you place the shape on an artboard this shouldn't occur. Hopefully you can use that workaround until I get a better fix in place.

**Comment by stefanspieler** [comment]
@kupe517 thanks for the info. works a bit better on a artboard. but not 100% as desired. Looking forward to your update. But anyway split shape is already a big timesaver.

**Comment by kupe517** [comment]
@stefanspieler I was able to find some time to rewrite the plugin! It _should_ be working much better now. I've tested it when the layer is both on an artboard and or just floating on the document and it seems to work fine both ways. Please open a new issue if you come across any problems!

**Comment by stefanspieler** [comment]
much better is understated! Works perfect. Thank you very much
