### ISSUE TITLE
Plugin not woking on Sketch 49.3

### ISSUE THREAD

**Issue by alekseyruzov** [kupe517/sketch-split-shape#3]
Hello! I start with rectangle, then I press "Split Shape" (or use Ctrl+Cmd+G), then nothing happens.

**Comment by kupe517** [comment]
Hi, do you have the latest version? Please make sure you have the latest as I know this was a bug prior but I am not able to reproduce now. If it is the latest can you me what the parent of the shape is? Artboard, Group, Symbol, etc?

**Comment by alekseyruzov** [comment]
Yes I do. I just installed the plugin via Runner. I am trying to use it with rectangle + artboard, within group and within symbol. No results. Absolutely nothing happens.

**Comment by kupe517** [comment]
Do you mind trying to install by downloading the plugin from Github? I'm not sure how Runner keeps the repo up to date so I just want to rule that out.

**Comment by alekseyruzov** [comment]
Yes I do. Same

**Comment by jcrouse26** [comment]
I am having the same issue, were you ever able to figure this out? i downloaded the plugin from github moments ago.

**Comment by kupe517** [comment]
Can one of you download DevTools and let me know of any errors that it is reporting? I am not able to reproduce the problem so need to debug to figure out what is happening with you guys. 
https://github.com/skpm/sketch-dev-tools

**Comment by jcrouse26** [comment]
Hi, this is what I get when I download Dev-Tools then try to run Split Shape:

ReferenceError: Can't find variable: require.
Plugin “script”, line 1:
» var sketch = require('sketch/dom');

TypeError: undefined is not an object (evaluating 'Settings.settingForKey')
line: 93
sourceURL: /Users/jcrouse/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Split Shape.sketchplugin/Contents/Sketch/script.js
column: 13
stack: setVariables@/Users/jcrouse/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Split Shape.sketchplugin/Contents/Sketch/script.js:93:13
createRectangleWindow@/Users/jcrouse/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Split Shape.sketchplugin/Contents/Sketch/script.js:154:14
settings@/Users/jcrouse/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Split Shape.sketchplugin/Contents/Sketch/script.js:55:36

Is that helpful? Apologies in advance as it's my first time doing this.

**Comment by kupe517** [comment]
Yes this helps! I suspected it may have something to do with that. Let me try and come up with a fix. Thanks for debugging!

**Comment by kupe517** [comment]
@jcrouse26 Are you running Sketch v49?

**Comment by kupe517** [comment]
I just pushed some new code which hopefully will fix the problem. Can you guys try pulling the latest and let me know if you still have the same problem? Thanks! @alekseyruzov @jcrouse26

**Comment by jcrouse26** [comment]
works for me! thank you!

**Comment by alekseyruzov** [comment]
Unfortunately, DevTools not working also. I've tried to roll back to Sketch 49.2, but still same problem.

**Comment by kupe517** [comment]
@alekseyruzov If devtools is not working for you either it may be something with your install. Maybe try completely deleting Sketch and reinstalling fresh?

**Comment by alekseyruzov** [comment]
Just deleted and reinstalled Sketch 49.3. No result. I have no idea what's wrong.

**Comment by kupe517** [comment]
@alekseyruzov Devtools doesn't work for you either? Do any plugins work for you? I remember there being a problem with permissions if you are installing via the App Store.

**Comment by alekseyruzov** [comment]
Devtools not working. Split Shape not working. Other plugins seems to be OK (I am using many of them every day). Permissions are repaired. That's weird )).

**Comment by kupe517** [comment]
Can you try debugging with the default Console app? Open Console and type in "Sketch" in the search box and then run the plugin and let me know what errors come up.

**Comment by alekseyruzov** [comment]
Ok. Here is the errors:

![2018-05-07_12-09-10](https://user-images.githubusercontent.com/4091432/39694279-7b46c642-51ef-11e8-9ae4-2f62244cac63.png)

**Comment by kupe517** [comment]
@alekseyruzov What version of OSX are you running? Have you updated in a while? It seems like you're getting an error because of Javascript ES6 formatting. Updating your computer may fix it.

**Comment by alekseyruzov** [comment]
El Capitan 10.11.6, not so old )).
