### ISSUE TITLE
Plugin not working on Sketch V 52.2

### ISSUE THREAD

**Issue by SeanMCummings** [kupe517/sketch-split-shape#5]
Hi!

When I go to split a shape using the command (or use Ctrl+Cmd+G), then nothing happens. Also tried 
or simply clicking "Split Shape" from the dropdown list it doesn't seem to work. Any chance you could look into this, as I believe it was working until the recent Sketch update. Thanks!

**Comment by kupe517** [comment]
Can you try deleting the plugin and reinstalling it? I'm running 52.2 and not seeing that problem
